from sqlmodel import SQLModel, Field
from typing import Optional
from datetime import datetime
import uuid


class UserBase(SQLModel):
    """
    Base model for user with common fields
    """
    email: str = Field(unique=True, nullable=False)
    name: Optional[str] = Field(default=None)


class User(UserBase, table=True):
    """
    User model for database storage

    Fields:
    - id: Unique user identifier generated by Better Auth
    - email: User's email address, used for authentication
    - name: User's display name
    - password: Hashed password for authentication
    - created_at: Account creation timestamp
    - updated_at: Last account update timestamp
    """
    __tablename__ = "users"

    id: str = Field(default_factory=lambda: str(uuid.uuid4()), primary_key=True)
    email: str = Field(unique=True, nullable=False, max_length=255)
    name: Optional[str] = Field(default=None, max_length=255)
    password: str = Field(nullable=False, max_length=255)  # Hashed password
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)


class UserCreate(UserBase):
    """
    Model for creating a new user
    """
    email: str
    password: str  # This will be hashed before storing
    name: Optional[str] = None


class UserUpdate(SQLModel):
    """
    Model for updating user information
    """
    name: Optional[str] = None


class UserPublic(UserBase):
    """
    Public model for user data (excludes sensitive information)
    """
    id: str
    created_at: datetime
    updated_at: datetime