"""
Add container_images table

Revision ID: de25f85aaa58
Revises: 1656465b3a69
Create Date: 2026-02-08 05:44:12.845500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'de25f85aaa58'
down_revision: Union[str, Sequence[str], None] = '1656465b3a69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('container_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('base_image', sa.String(length=255), nullable=False),
    sa.Column('optimization_level', sa.String(length=50), nullable=False),
    sa.Column('dockerfile_content', sa.Text(), nullable=False),
    sa.Column('image_size', sa.Float(), nullable=True),
    sa.Column('security_score', sa.Float(), nullable=True),
    sa.Column('built_status', sa.String(length=20), nullable=True),
    sa.Column('built_error', sa.Text(), nullable=True),
    sa.Column('built_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_container_images_created_at'), 'container_images', ['created_at'], unique=False)
    op.create_index(op.f('ix_container_images_user_id'), 'container_images', ['user_id'], unique=False)
    op.create_index('uq_container_images_user_name', 'container_images', ['user_id', 'name'], unique=True)
    op.create_index('ix_container_images_built_status', 'container_images', ['built_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_container_images_built_status', table_name='container_images')
    op.drop_index('uq_container_images_user_name', table_name='container_images')
    op.drop_index(op.f('ix_container_images_user_id'), table_name='container_images')
    op.drop_index(op.f('ix_container_images_created_at'), table_name='container_images')
    op.drop_table('container_images')
    # ### end Alembic commands ###